title: Maialen I. A.
description: <strong>DATA ENGINEERING & ARCHITECTURE</strong><br> I build scalable data architectures and pipelines to turn raw data into impact.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

paginate_path: "/blog/page:num/"  # Pagination page path
paginate: 20

plugins:
  - jekyll-paginate

sass:
  style: compressed
